AnimaRating:
  safe: "safe,"
  sensitive: "sensitive,"
  nsfw: "nsfw,"
  explicit: "explicit,"
推奨設定:
  Anima1.0-base:
    Euler: "Steps:30.0,Sampler: Euler,CFG scale: 5.0,Schedule type: Beta,"
    ER_SDE: "Steps:30.0,Sampler: ER SDE,CFG scale: 5.0,Schedule type: Beta,"
    Turbo: "Steps:10.0,Sampler: ER SDE,CFG scale: 1.0,Schedule type: Beta,"
  NovaAnimeAM:
    Euler: "Steps:25.0,Sampler: Euler a,CFG scale: 5.0,Schedule type: Normal,"
  OOO_Anima:
    Euler: "Steps:40.0,Sampler: Euler a,CFG scale: 4.0,Schedule type: Normal,"
  Hassaku Anima:
    Euler: "Steps:40.0,Sampler: ER SDE,CFG scale: 5.0,Schedule type: Normal,"
    
